# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_choose(object):
    def setupUi(self, Form_choose):
        Form_choose.setObjectName("Form_choose")
        Form_choose.resize(800, 601)
        self.centralwidget = QtWidgets.QWidget(Form_choose)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_choose = QtWidgets.QFrame(self.centralwidget)
        self.frame_choose.setGeometry(QtCore.QRect(210, 70, 323, 310))
        self.frame_choose.setStyleSheet("#frame_choose{\n"
"background-image: url(:/弹窗/素材/弹窗11.png);\n"
"border-radius:20px; /* 边框半径 */}\n"
"")
        self.frame_choose.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_choose.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_choose.setObjectName("frame_choose")
        self.pushButton_confirm = QtWidgets.QPushButton(self.frame_choose)
        self.pushButton_confirm.setGeometry(QtCore.QRect(120, 250, 93, 28))
        self.pushButton_confirm.setStyleSheet("border-radius: 10px; /* 边框半径 */\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(9, 45, 79);")
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.label_leixing = QtWidgets.QLabel(self.frame_choose)
        self.label_leixing.setGeometry(QtCore.QRect(120, 60, 91, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_leixing.setFont(font)
        self.label_leixing.setObjectName("label_leixing")
        self.layoutWidget = QtWidgets.QWidget(self.frame_choose)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 110, 132, 96))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_shipan = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("等线")
        self.radioButton_shipan.setFont(font)
        self.radioButton_shipan.setIconSize(QtCore.QSize(57, 30))
        self.radioButton_shipan.setObjectName("radioButton_shipan")
        self.verticalLayout.addWidget(self.radioButton_shipan)
        self.radioButton_xueguan = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("等线")
        self.radioButton_xueguan.setFont(font)
        self.radioButton_xueguan.setObjectName("radioButton_xueguan")
        self.verticalLayout.addWidget(self.radioButton_xueguan)
        self.radioButton_both = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_both.setMinimumSize(QtCore.QSize(130, 30))
        self.radioButton_both.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.radioButton_both.setFont(font)
        self.radioButton_both.setObjectName("radioButton_both")
        self.verticalLayout.addWidget(self.radioButton_both)
        Form_choose.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form_choose)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        Form_choose.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form_choose)
        self.statusbar.setObjectName("statusbar")
        Form_choose.setStatusBar(self.statusbar)

        self.retranslateUi(Form_choose)
        self.pushButton_confirm.clicked.connect(Form_choose.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form_choose)

    def retranslateUi(self, Form_choose):
        _translate = QtCore.QCoreApplication.translate
        Form_choose.setWindowTitle(_translate("Form_choose", "MainWindow"))
        self.pushButton_confirm.setText(_translate("Form_choose", "确定"))
        self.label_leixing.setText(_translate("Form_choose", "影像类型"))
        self.radioButton_shipan.setText(_translate("Form_choose", "视盘"))
        self.radioButton_xueguan.setText(_translate("Form_choose", "血管"))
        self.radioButton_both.setText(_translate("Form_choose", "视盘和血管"))
import picture_rc
