# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logn.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_logn(object):
    def setupUi(self, Form_logn):
        Form_logn.setObjectName("Form_logn")
        Form_logn.resize(1300, 820)
        self.frame_logn = QtWidgets.QFrame(Form_logn)
        self.frame_logn.setGeometry(QtCore.QRect(10, 10, 1280, 800))
        self.frame_logn.setStyleSheet("\n"
"#frame_logn{\n"
"background-image: url(:/lognpic/素材/背景.png);\n"
"border-radius:15px;}\n"
"")
        self.frame_logn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_logn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_logn.setObjectName("frame_logn")
        self.pushButton_logn = QtWidgets.QPushButton(self.frame_logn)
        self.pushButton_logn.setGeometry(QtCore.QRect(610, 620, 91, 90))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_logn.setFont(font)
        self.pushButton_logn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_logn.setStyleSheet("border-radius: 10px; /* 边框半径 */\n"
"background-image: url(:/新前缀/素材/登录 (5).png);\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_logn.setObjectName("pushButton_logn")
        self.pushButton_help = QtWidgets.QPushButton(self.frame_logn)
        self.pushButton_help.setGeometry(QtCore.QRect(1150, 640, 91, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_help.setFont(font)
        self.pushButton_help.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_help.setStyleSheet("border-radius: 5px; /* 边框半径 */\n"
"background: white; /* 背景颜色 */\n"
"background-color: rgb(230, 230, 230);\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_help.setObjectName("pushButton_help")
        self.lineEdit_user = QtWidgets.QLineEdit(self.frame_logn)
        self.lineEdit_user.setGeometry(QtCore.QRect(440, 465, 441, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setStyleSheet("background-color: rgb(234, 234, 239);")
        self.lineEdit_user.setText("")
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame_logn)
        self.lineEdit_password.setGeometry(QtCore.QRect(440, 545, 441, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("background-color: rgb(234, 234, 239);\n"
"\n"
"font: 12pt \"宋体\";")
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setReadOnly(False)
        self.lineEdit_password.setPlaceholderText("")
        self.lineEdit_password.setClearButtonEnabled(True)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_title = QtWidgets.QLabel(self.frame_logn)
        self.label_title.setGeometry(QtCore.QRect(410, 160, 831, 161))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(51)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.label_title.setObjectName("label_title")
        self.label_user = QtWidgets.QLabel(self.frame_logn)
        self.label_user.setGeometry(QtCore.QRect(340, 460, 91, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_user.setFont(font)
        self.label_user.setStyleSheet("color: rgb(0, 0, 1);")
        self.label_user.setObjectName("label_user")
        self.label_password = QtWidgets.QLabel(self.frame_logn)
        self.label_password.setGeometry(QtCore.QRect(340, 540, 91, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_password.setFont(font)
        self.label_password.setStyleSheet("color: rgb(0, 0, 1);")
        self.label_password.setObjectName("label_password")
        self.label_logo = QtWidgets.QLabel(self.frame_logn)
        self.label_logo.setGeometry(QtCore.QRect(20, 20, 83, 83))
        self.label_logo.setStyleSheet("background-image: url(:/新前缀/素材/Logo.png);")
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("C:/Users/yvette/.designer/backup/Logo.png"))
        self.label_logo.setObjectName("label_logo")
        self.label_version = QtWidgets.QLabel(self.frame_logn)
        self.label_version.setGeometry(QtCore.QRect(920, 340, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgb(0,0, 1);")
        self.label_version.setObjectName("label_version")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame_logn)
        self.pushButton_exit.setGeometry(QtCore.QRect(1170, 690, 60, 60))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("border-radius: 10px; /* 边框半径 */\n"
"\n"
"background-image: url(:/新前缀/素材/退出登录.png);\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_exit.setText("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label_user_img = QtWidgets.QLabel(self.frame_logn)
        self.label_user_img.setGeometry(QtCore.QRect(290, 465, 41, 41))
        self.label_user_img.setStyleSheet("background-image: url(:/新前缀/素材/登录 (4).png);")
        self.label_user_img.setText("")
        self.label_user_img.setPixmap(QtGui.QPixmap("C:/Users/yvette/.designer/backup/登录 (4).png"))
        self.label_user_img.setObjectName("label_user_img")
        self.label_password_img = QtWidgets.QLabel(self.frame_logn)
        self.label_password_img.setGeometry(QtCore.QRect(290, 545, 41, 41))
        self.label_password_img.setStyleSheet("background-image: url(:/新前缀/素材/密码登录.png);")
        self.label_password_img.setText("")
        self.label_password_img.setPixmap(QtGui.QPixmap("C:/Users/yvette/.designer/backup/密码登录.png"))
        self.label_password_img.setObjectName("label_password_img")
        self.label_titlepicture = QtWidgets.QLabel(self.frame_logn)
        self.label_titlepicture.setGeometry(QtCore.QRect(110, 170, 291, 131))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(51)
        font.setBold(True)
        font.setWeight(75)
        self.label_titlepicture.setFont(font)
        self.label_titlepicture.setStyleSheet("\n"
"image: url(:/新前缀/素材/login.png);")
        self.label_titlepicture.setText("")
        self.label_titlepicture.setObjectName("label_titlepicture")

        self.retranslateUi(Form_logn)
        QtCore.QMetaObject.connectSlotsByName(Form_logn)

    def retranslateUi(self, Form_logn):
        _translate = QtCore.QCoreApplication.translate
        Form_logn.setWindowTitle(_translate("Form_logn", "Form"))
        self.pushButton_logn.setText(_translate("Form_logn", "登录"))
        self.pushButton_help.setText(_translate("Form_logn", "帮 助"))
        self.label_title.setText(_translate("Form_logn", "医学影像分割系统"))
        self.label_user.setText(_translate("Form_logn", "用户："))
        self.label_password.setText(_translate("Form_logn", "密码："))
        self.label_version.setText(_translate("Form_logn", "—— v.1.0"))
import picture_rc
